trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: InstallAndTest
  jobs:
  - job: InstallAndTestJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: npm install
      displayName: 'Install Dependencies'

    - script: npm test
      displayName: 'Run Unit Tests'

- stage: RunSonarQubeAnalysis
  jobs:
  - job: RunSonarQubeAnalysisJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sonar-scanner -Dsonar.projectKey=BragatheeshJ_madv \
        -Dsonar.sources=src \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=738b59952d0c82460d03b1c69ff37bbc9a5e63f9
      displayName: 'Run SonarQube Analysis'

- stage: PublishSonarQubeAnalysis
  jobs:
  - job: PublishSonarQubeAnalysisJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
      displayName: 'Publish SonarQube Analysis'