trigger: 
  - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: InstallDependencies
  jobs:
  - job: NpmInstall
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'npm install'

- stage: Build
  jobs:
  - job: NpmBuild
    steps:
    - script: 
        # npm run build
      displayName: 'npm build'

- stage: Test
  jobs:
  - job: UnitTest
    steps:
    - script: |
        npm run test
      displayName: 'Run Unit Tests'

- stage: RunSonarQubeAnalysis
  jobs:
  - job: RunSonarQubeAnalysisJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sonar-scanner -Dsonar.projectKey=BragatheeshJ_madv \
        -Dsonar.sources=src \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=738b59952d0c82460d03b1c69ff37bbc9a5e63f9
      displayName: 'Run SonarQube Analysis'

- stage: PublishSonarQubeAnalysis
  jobs:
  - job: PublishSonarQubeAnalysisJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
      displayName: 'Publish SonarQube Analysis'